---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by THeartnet.
--- DateTime: 10/11/2022 01:01
RCDetonator = {};

---@class RCDetonator
RCDetonator = ISBaseObject:derive("RCDetonator");

RCDetonator.detonationType = {};
RCDetonator.vehicleHash = {};
RCDetonator.recentlyExplodedHash = {};
RCDetonator.crashedHash = {};
RCDetonator.recentTimer = 0;
RCDetonator.recentInterval = 80;
RCDetonator.recentSmokes = {};

require "zCommon"

function RCDetonator.getRecentCount()
    local resultCount = 0;
    for _, v in ipairs(RCDetonator.recentSmokes) do
        if v then
            resultCount = resultCount + 1;
        end
    end

    return resultCount;
end

function RCDetonator:getDetonationType()
    return self.detonationType;
end

function RCDetonator:new(x, y, z, rectObject)
    local rcDetonator = {};
    setmetatable(rcDetonator, self);
    self.__index = self;

    rcDetonator.x = x;
    rcDetonator.y = y;
    rcDetonator.z = z;
    rcDetonator.oppositeSquare = nil;
    rcDetonator.rectObject = rectObject;
    local modData = rectObject:getModData();
    rcDetonator.type = modData["rect_type"];

    return rcDetonator;
end

function RCDetonator:activate(player)
    self.executioner = player;
    self.activated = true;
end

function RCDetonator:applyExplosionInitialEffects(detonationSquare)

end

function RCDetonator:applyExplosionMidEffects(detonationSquare)

end

function RCDetonator:applyExplosionPostEffects(detonationSquare)

end

function RCDetonator:explode()

end