---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by THeartnet.
--- DateTime: 9/26/2022 19:19
---
require "BuildingObjects/ISBuildingObject"

---@class RCExplosive : ISSimpleFurniture
RCExplosive = ISBuildingObject:derive("RCExplosive");

function RCExplosive:new(name, square, remoteId, player, explosiveItem)
    local rcExplosive = {};
    setmetatable(rcExplosive, self);
    self.__index = self;
    rcExplosive:init();

    rcExplosive.explosiveSource = explosiveItem;
    rcExplosive.name = name;
    rcExplosive.targetSquare = square;
    rcExplosive.remoteId = remoteId;
    rcExplosive.player = player;

    rcExplosive.canBarricade = false;
    rcExplosive.dismantable = false;
    rcExplosive.blockAllTheSquare = false;
    rcExplosive.canBeAlwaysPlaced = true;
    rcExplosive.skipBuildAction = true;
    rcExplosive:setDragNilAfterPlace(true);
    rcExplosive.canPassThrough = true;
    rcExplosive.isWallLike = true;
    rcExplosive.noNeedHammer = true;
    rcExplosive.needToBeAgainstWall = true;

    return rcExplosive;
end
