---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by THeartnet.
--- DateTime: 10/6/2022 06:12
---
local _getBarricadeAble = function(x, y, z, index)
    local sq = getCell():getGridSquare(x, y, z);
    if sq and index >= 0 and index < sq:getObjects():size() then
        local o = sq:getObjects():get(index);
        if instanceof(o, 'BarricadeAble') then
            return o;
        end
    end
    return nil;
end

function OnExplosiveBarricadeCommand(module, command, player, args)
    if module ~= "Explosive" then return end
    if command ~= "ExplosiveBarricade" then return end

    --print("Explosive!");
    local object = _getBarricadeAble(args.x, args.y, args.z, args.index);
    if object then
        if (object:isBarricaded() ~= true) then
            if args.isDoor == true then
                if object:IsOpen() == true then
                    object:ToggleDoor(player);
                end
            end

            local barricade = IsoBarricade.AddBarricadeToObject(object, player);
            if barricade then
                local plank = InventoryItemFactory.CreateItem('Base.Plank');
                plank:setCondition(args.condition);
                barricade:addPlank(player, plank);
                barricade:transmitCompleteItemToClients();
            end
        end
    end

    --print("north: "..tostring(args.north)..", sprite: "..tostring(args.sprite));
    local cell = getWorld():getCell();
    local targetSquare = cell:getGridSquare(args.targetX, args.targetY, args.targetZ);
    local zJavaObject = IsoThumpable.new(cell, targetSquare, args.sprite, args.north, args.explosiveObject);
    --print("New IsoObject: "..tostring(zJavaObject));

    buildUtil.setInfo(zJavaObject, args.explosiveObject);
    zJavaObject:setIsThumpable(false);
    zJavaObject:setIsDoor(false);
    zJavaObject:setIsStairs(false);

    --print("Name of our IsoUnThumpable: "..tostring(zJavaObject:getName()));

    -- add the item to the ground
    targetSquare:AddSpecialObject(zJavaObject);
    zJavaObject:transmitCompleteItemToClients();
    triggerEvent("OnObjectAdded", zJavaObject);
end

function OnExplosiveOnlyCommand(module, command, player, args)
    if module ~= "Explosive" then return end
    if command ~= "ExplosiveOnly" then return end

    --print("north: "..tostring(args.north)..", sprite: "..tostring(args.sprite));
    local cell = getWorld():getCell();
    local targetSquare = cell:getGridSquare(args.targetX, args.targetY, args.targetZ);
    local zJavaObject = IsoThumpable.new(cell, targetSquare, args.sprite, args.north, args.explosiveObject);
    --print("New IsoObject: "..tostring(zJavaObject));

    buildUtil.setInfo(zJavaObject, args.explosiveObject);
    zJavaObject:setIsThumpable(false);
    zJavaObject:setIsDoor(false);
    zJavaObject:setIsStairs(false);

    --print("Name of our IsoUnThumpable: "..tostring(zJavaObject:getName()));
    -- add the item to the ground
    targetSquare:AddSpecialObject(zJavaObject);
    zJavaObject:transmitCompleteItemToClients();
    triggerEvent("OnObjectAdded", zJavaObject);
end

Events.OnClientCommand.Add(OnExplosiveOnlyCommand);
Events.OnClientCommand.Add(OnExplosiveBarricadeCommand);