---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by THeartnet.
--- DateTime: 12/11/2022 12:14

require "RCExplosive.server.RCExplosive"

---@class RCExplosiveBox : RCExplosive
RCExplosiveBox = RCExplosive:derive("RCExplosiveBox");

RCExplosiveBox.explosiveSprites = {
    north = 'RC_ExplosiveChest_0',
    west = 'RC_ExplosiveChest_3',
    east = 'RC_ExplosiveChest_1',
    south = 'RC_ExplosiveChest_2'
};

RCExplosiveBox.boxName = "RCExplosiveBox";
RCExplosiveBox.chargeName = "RCDynamite";

RCExplosiveBox.plantingSounds = {
    activation = 'RCC4ActivationProcess',
    plantedMale = 'RCC4PlantingMale',
    plantedFemale = 'RCC4PlantingFemale'
};

RCExplosiveBox.ExplosionDamage = 300;
RCExplosiveBox.ExplosionBlastSquares = 3
RCExplosiveBox.ExplosionSplashRadius = 3;
RCExplosiveBox.ExplosionSectionCount = 3;


function RCExplosiveBox:new(name, square, remoteId, player, explosiveItem)
    local explosiveBox = RCExplosive.new(self, name, square, remoteId, player, explosiveItem);
    setmetatable(explosiveBox, self);
    self.__index = self;
    explosiveBox:init();

    explosiveBox:setSprite(RCExplosiveBox.explosiveSprites.west);
    explosiveBox:setNorthSprite(RCExplosiveBox.explosiveSprites.north);
    explosiveBox:setEastSprite(RCExplosiveBox.explosiveSprites.east);
    explosiveBox:setSouthSprite(RCExplosiveBox.explosiveSprites.south);
    explosiveBox.modData['need:Base.RCExplosiveDynamite'] = 1;

    explosiveBox.controllerId = nil;

    return explosiveC4;
end