---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by THeartnet.
--- DateTime: 9/27/2022 00:43
---
RCContextMenu = {};
RCContextMenu.plantExplosives = function(explosiveItem, targetSquare, player, explosiveName, linkedRemoteId)
    --print("Explosives planted");

    local explosiveC4 = RCExplosiveC4:new(explosiveName, targetSquare, linkedRemoteId, player, explosiveItem);
    getCell():setDrag(explosiveC4, player);
end

local function onMenu(player, context, worldObjects)
    --print("on Menu");
    local currentPlayer = getSpecificPlayer(player);
    local playerInv = currentPlayer:getInventory();
    local clickedSquare;

    for _,object in ipairs(worldObjects) do
        clickedSquare = object:getSquare();
        if clickedSquare then break end
    end

    if not clickedSquare then return end

    local target = clickedSquare;
    local explosiveC4Item = playerInv:getFirstEvalRecurse(RCExplosiveC4.predicateExplosive);

    if explosiveC4Item then
        local linkedRemoteId = explosiveC4Item:getRemoteControlID();
        if linkedRemoteId ~= -1 then
            context:addOption(getText("Plant explosives"), explosiveC4Item, RCContextMenu.plantExplosives, target, player, explosiveC4Item:getType(),linkedRemoteId);
        end
    end
end

Events.OnFillWorldObjectContextMenu.Add(onMenu);



