require "Items/ProceduralDistributions"
-- CamaroSStire3
table.insert(ProceduralDistributions.list["GarageMechanics"].items, "Base.CamaroSStire3");
table.insert(ProceduralDistributions.list["GarageMechanics"].items, 0.3);
table.insert(ProceduralDistributions.list["CrateMechanics"].items, "Base.CamaroSStire3");
table.insert(ProceduralDistributions.list["CrateMechanics"].items, 0.2);
table.insert(ProceduralDistributions.list["GarageTools"].items, "Base.CamaroSStire3");
table.insert(ProceduralDistributions.list["GarageTools"].items, 0.5);
-- 69camaroFrontBumper1
table.insert(ProceduralDistributions.list["GarageMechanics"].items, "Base.69camaroFrontBumper1");
table.insert(ProceduralDistributions.list["GarageMechanics"].items, 0.3);
table.insert(ProceduralDistributions.list["CrateMechanics"].items, "Base.69camaroFrontBumper1");
table.insert(ProceduralDistributions.list["CrateMechanics"].items, 0.2);
table.insert(ProceduralDistributions.list["GarageTools"].items, "Base.69camaroFrontBumperA");
table.insert(ProceduralDistributions.list["GarageTools"].items, 0.3);
-- 69camaroSpoiler0
table.insert(ProceduralDistributions.list["GarageMechanics"].items, "Base.69camaroSpoiler0");
table.insert(ProceduralDistributions.list["GarageMechanics"].items, 0.2);
table.insert(ProceduralDistributions.list["CrateMechanics"].items, "Base.69camaroSpoiler0");
table.insert(ProceduralDistributions.list["CrateMechanics"].items, 0.2);